TEAM-2NE1/steach-front

src/components/main/Subjects.tsx
src/components/teacher/LectureReport.tsx

-  선생님 내 강의실 작업 진행 60퍼 완료
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 선생님 내 강의실 페이지 필수 페이지 라우트로 연결 후 현재 강의 리포트 작업 진행 중

---

src/components/teacher/CreateQuiz.tsx

- 퀴즈 페이지 재 업로드
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 페이지 재 업로드

---

src/components/main/Navbar.tsx
src/components/user/SignUp/StudentSignUp.tsx
src/pages/user/LoginPage.tsx
src/pages/user/SignUpPage.tsx
src/store.tsx
src/store/AuthSlice.tsx
src/store/lecturesSlice.tsx

- [] 코드 수정
- 회원가입, 로그인 API 통신 작업 시도 중
<br><br>
- axios를 이용한 API 통신에 대해 공부를 하면서 기능 구현 중, redux thunk에 대해 공부할 필요가 있음.
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 회원가입, 로그인 API 통신 작업 진행 중

---

src/components/user/SignUp/StudentSignUp.tsx
src/store.tsx
src/store/AuthSlice.tsx

- 회원가입 API 통신 수정 작업 중
<br><br>
axios 통신은 비동기적으로 진행되기 때문에 redux-toolkit Thunk를 이용하여 비동기 로직을 구성 중
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 회원가입 API 통신 작업 진행 중

---

src/components/lecture/SignUp.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/pages/user/LoginPage.tsx
src/store.tsx
src/store/TeacherAuthSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 선생님 회원가입 완성

---

src/api/loginApi.tsx
src/components/main/Navbar.tsx
src/components/user/SignUp/StudentSignUp.tsx
src/main.tsx
src/pages/user/LoginPage.tsx
src/store.tsx
src/store/AuthSlice.tsx

- 회원가입, 로그인, 로그아웃 로직 완료, 로그인 통합은 아직 진행 중
<br><br>
- 기존 코드에서는 회원가입도 작성이 안되었으나 회원가입, 로그인, 로그아웃 로직이 일단 돌아가도록 짜놨음.
- 로그인을 합치려고 했으나 slice의 상태가 바뀌지 않음 다시 시도해볼 필요가 있다.
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 회원가입, 로그인, 로그아웃 로직 완료, 로그인 통합은 아직 진행 중

---

src/components/lecture/SignUp.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/store/TeacherAuthSlice.tsx
src/store/lecturesSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

강의등록 axios 테스트, 403에러 떠서 도중에 작업 중단

---

src/api/loginApi.tsx
src/components/user/SignUp/StudentSignUp.tsx
src/pages/user/LoginPage.tsx
src/store/AuthSlice.tsx

- 학생 회원가입, 로그인 작업 완료
<br><br>
- user의 정보를 하나의 slice에서 관리를 하는 것이 좋을 듯하여 합치려고 함.
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 학생 회원가입, 로그인 작업 완료 후 선생님 측과 합치기 위한 작업 전

---

src/components/lecture/SignUp.tsx
src/components/main/HotLectures.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/store.tsx
src/store/lectureslist.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat:강의상세페이지, 메인페이지 강의 get호출 작업중..

---

src/App.tsx
src/components/lecture/Detail.tsx
src/components/lecture/SignUp.tsx
src/components/main/HotLectures.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/store/lecturesSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의등록 완성, 강의상세 작업중.

---

src/App.tsx
src/api/main/mainAPI.ts
src/api/user/userAPI.ts
src/components/main/Carousel.tsx
src/components/main/navBar/Navbar.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoUpdateForm.tsx
src/pages/user/LoginPage.tsx
src/store/userInfo/AuthSlice.tsx
src/store/userInfo/profileSlice.tsx

- feat: 로그인 상태 수정 및 내정보 각 아이디 별로 정보가 출력되도록 수정하였음
<br><br>
- 로그인 상태를 localStorage에 저장을 하고 localStorage에서 로그인 상태를 가져오도록 코드를 작성하였음.
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 로그인 상태 수정 및 내정보 각 아이디 별로 정보가 출력되도록 수정하였음

---

src/api/user/userAPI.ts
src/components/teacher/teacherMyInfo/TeacherMyInfo.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoForm.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoUpdateForm.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/store/userInfo/profileSlice.tsx

- [] 코드 수정
- feat: 선생님 내 정보 수정 API 통신 완료(수정이 조금 더 필요함)
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 선생님 내 정보 수정 API 통신 완료(수정이 조금 더 필요함)

---

src/App.tsx
src/api/lecture/curriculumAPI.ts
src/components/lecture/Detail.tsx
src/components/main/HotLectures.tsx
src/components/main/navBar/NavbarStudent.tsx
src/store/lecturesSlice.tsx
src/store/lectureslist.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의 상세 페이지 axios 및 디자인 작업중

---

src/api/lecture/curriculumAPI.ts

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat:빨간줄 수정

---

src/components/lecture/Detail.tsx
src/components/lecture/SignUp.tsx
src/components/main/FroalaEditor.tsx
src/components/main/HotLectures.tsx
src/components/main/LatestLectures.tsx
src/components/teacher/CreateQuiz.tsx
src/components/teacher/CurriculumList.tsx
src/components/teacher/Detail.tsx
src/components/teacher/DetailUpdate.tsx
src/components/teacher/TeacherUpdateMyInfo.tsx
src/pages/lecture/UpdatePage.tsx
src/pages/teacher/TeacherMyRoomPage.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat:에러 다 지움

---

src/api/user/userAPI.ts
src/store/curriculaSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 다시 푸시

---

src/api/BASE_URL.ts
src/api/lecture/curriculumAPI.ts
src/api/lecture/lectureAPI.ts
src/api/lecture/quizAPI.ts
src/api/main/mainAPI.ts
src/api/meeting/meetingAPI.ts
src/api/meeting/meetingDataAPI.ts
src/api/statictis/statictis.ts
src/api/user/userAPI.ts
src/components/teacher/teacherMyLecture/TeacherMyLectureList.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureListButton.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureListModal.tsx

- feat: 상철 URL 요청 커밋
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 상철 URL 요청 커밋

---

src/api/lecture/curriculumAPI.ts
src/api/lecture/lectureAPI.ts
src/api/lecture/quizAPI.ts
src/api/main/mainAPI.ts
src/api/meeting/meetingAPI.ts
src/api/meeting/meetingDataAPI.ts
src/api/statictis/statictis.ts
src/api/user/userAPI.ts
src/store/curriculaSlice.tsx

- feat: 강의 수정 기능 구현 중 및 BASE_URL 설정 파일 생성
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의 수정 기능 구현 중

---

src/api/lecture/curriculumAPI.ts
src/components/lecture/Detail.tsx
src/store/curriculaSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fear: 강의상세 완성

---

src/App.tsx
src/api/BASE_URL.ts
src/api/lecture/curriculumAPI.ts
src/api/lecture/lectureAPI.ts
src/api/lecture/quizAPI.ts
src/api/main/mainAPI.ts
src/api/meeting/meetingAPI.ts
src/api/meeting/meetingDataAPI.ts
src/api/statictis/statictis.ts
src/api/user/userAPI.ts
src/components/lecture/Detail.tsx
src/components/lecture/Update.tsx
src/interface/Curriculainterface.tsx
src/store/curriculaSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의상세페이지 작업도중

---

package-lock.json
package.json

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

depend: 의존성 추가

---

src/store/userInfo/AuthSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

refactor: 임폴트 경로 변경

---

src/api/user/userAPI.ts
src/interface/auth/AuthInterface.tsx
src/store/userInfo/AuthSlice.tsx
vite.config.ts

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix: 에러 햏결

---

src/pages/sub/Cat.tsx
src/pages/sub/Man.tsx
src/pages/sub/Reva.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix: error 해결

---

api/lecture/curriculumAPI.ts
api/lecture/lectureAPI.ts
api/lecture/quizAPI.ts
api/main/mainAPI.ts
api/meeting/meetingAPI.ts
api/meeting/meetingDataAPI.ts
package-lock.json
package.json
src/api/BASE_URL.ts
src/api/lecture/curriculumAPI.ts

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix: 배포 에러 해결

---

src/components/quiz/FloatingEmoji.tsx
src/components/quiz/QuizBlock.tsx
src/components/quiz/floatingHeart.css
src/components/quiz/goUp.css

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 화면 생성

---

src/components/main/Subjects.tsx
src/components/main/search/SearchCategoryMenu.tsx
src/pages/main/SearchPage.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat : home 화면에서 강의리스트 보기 연결 완료

---

CD-TEST.txt
dockerfile
package.json
src/components/main/Footer.tsx
src/components/main/search/SearchSwitch.tsx
src/pages/main/SearchPage.tsx
src/pages/user/LoginPage.tsx

- Loginpage 로그인 컨테이너가 화면 밖으로 튀어나가는 오류 수정
- Footer bar가 로그인 페이지 중간에 있는 오류 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

refactor: Loginpage 로그인 컨테이너 위치 수정, Footer 하단 고정

---

src/api/lecture/curriculumAPI.ts
src/components/main/navBar/NavbarLogin.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/main/search/SearchPagination.tsx
src/components/main/search/SearchSwitch.tsx
src/interface/search/SearchInterface.tsx
src/pages/main/SearchPage.tsx
src/store/SearchSlice.tsx

- feat: 커리큘럼 검색 네브바 연동 하는 중 
<br><br>
- 기존에 네브바와 연동하기 전에 로컬 상태에서 관리를 하다보니 많이 복잡해지고 로직이 비효율적으로 되어서 리덕스를 이용하여 저장소에서 상태를 관리하여  연동을 좀 더 매끄럽게 하려고 기능 구현 및 코드 수정 중
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 커리큘럼 검색 네브바 연동 중

---

src/pages/main/SearchPage.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat:충돌 해결 푸씨

---

src/components/lecture/Detail.tsx
src/components/main/HotLectures.tsx
src/components/main/LatestLectures.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureList.tsx
src/interface/Curriculainterface.tsx
src/store/curriculaSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat:강의상세 디자인, 로직 수정 / 선생프로필 완성, 최신강의리스트 완성

---

src/api/user/userAPI.ts
src/components/main/navBar/Navbar.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/user/SignUp/StudentSignUp.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/interface/auth/AuthInterface.tsx
src/pages/user/LoginPage.tsx
src/store/userInfo/AuthSlice.tsx

- fixed: 회원가입 아이디 닉네임 중복 확인 로직 구현 및 로그인 로그아웃 새로고침 로직 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fixed: 회원가입 아이디 닉네임 중복 확인 로직 구현 및 로그인 로그아웃 새로고침 로직 수정

---

src/components/lecture/Detail.tsx
src/components/lecture/Update.tsx
src/components/main/HotLectures.tsx
src/components/main/LatestLectures.tsx
src/components/main/navBar/Navbar.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureList.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureListModal.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/interface/search/SearchInterface.tsx
src/store.tsx
src/store/SearchSlice.tsx
src/store/userInfo/AuthSlice.tsx

- fixed: 로그아웃 기능 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fixed: 로그아웃 기능 수정

---

src/components/quiz/QuizBlock.tsx
src/components/quiz/QuizListComponent.tsx
src/components/quiz/StatisticsChart.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 랭킹 통신코드 작성

---

src/App.tsx
src/api/BASE_URL.ts
src/api/lecture/curriculumAPI.ts
src/api/lecture/lectureAPI.ts
src/api/lecture/quizAPI.ts
src/api/user/userAPI.ts
src/components/student/studentMyInfo/StudentMyInfoForm.tsx
src/components/student/studentMyInfo/StudentMyInfoUpdateForm.tsx
src/components/teacher/quiz/FetchQuiz.tsx
src/components/teacher/quiz/NoQuiz.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoForm.tsx
src/components/teacher/teacherMyLecture/TeacherMyCurricula.tsx
src/pages/quiz/QuizManagementPage.tsx
src/pages/teacher/TeacherProfilePage.tsx
src/store/QuizSlice.tsx
src/store/userInfo/AuthSlice.tsx
src/store/userInfo/StudentProfileSlice.tsx
src/store/userInfo/TeacherProfileSlice.tsx

- fixed: 퀴즈 없을때 화면 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fixed: 퀴즈 없을때 화면 수정

---

src/components/quiz/QuizBlock.tsx
src/components/quiz/QuizListComponent.tsx
src/components/quiz/RankingList.tsx
src/components/quiz/StatisticsChart.tsx

부드럽게!
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

design: score도 부드럽게 변경되도록 추가

---

src/App.tsx
src/api/lecture/quizAPI.ts
src/components/quiz/QuizBlock.tsx
src/components/quiz/QuizDrawer.tsx
src/components/teacher/quiz/FetchQuiz.tsx

- feat: 퀴즈 drawer 구현
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 drawer 구현

---

src/components/main/Subjects.tsx
src/components/main/modal/DeleteModal.tsx
src/components/main/navBar/NavbarLogin.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/main/search/SearchCategoryMenu.tsx
src/components/student/CareerRecommendation.tsx
src/components/student/MyInfo.tsx
src/components/student/MyLecturePreference.tsx
src/components/student/studentMyInfo/StudentMyInfoForm.tsx
src/components/student/studentMyInfo/StudentMyInfoUpdateForm.tsx
src/components/student/studentMyInfo/StudentUpdateInfoModal.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoUpdateForm.tsx

- fixed: 학생 내 정보 폼 디자인 수정 및 학생 내 정보 폼에 강의 선호도, 진로추천 추가해 놓았음.
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fixed: 학생 내 정보 폼 디자인 수정

---

src/api/BASE_URL.ts
src/api/lecture/curriculumAPI.ts
src/components/lecture/Detail.tsx
src/components/lecture/SignUp.tsx
src/components/lecture/Update.tsx
src/store/CurriculaSlice.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의 수정 디테일 등록 끝냄

---

src/App.tsx
src/components/lecture/SignUp.tsx
src/components/lecture/Update.tsx
src/components/main/modal/DeleteModal.tsx
src/components/main/navBar/NavbarLogin.tsx
src/components/main/navBar/NavbarStudent.tsx
src/components/main/navBar/NavbarTeacher.tsx
src/components/main/search/SearchCard.tsx
src/components/student/studentMyInfo/StudentMyInfoForm.tsx
src/components/student/studentMyInfo/StudentMyInfoUpdateForm.tsx
src/components/teacher/LectureReport.tsx
src/components/teacher/quiz/CreateQuiz.tsx
src/components/teacher/quiz/FetchQuiz.tsx
src/components/teacher/quiz/NoQuiz.tsx
src/components/teacher/quiz/PatchQuiz.tsx
src/components/teacher/teacherMyInfo/TeacherMyInfoUpdateForm.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureList.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureListButton.tsx
src/components/user/SignUp/TeacherSignUp.tsx
src/main.tsx
src/pages/main/SearchPage.tsx
src/pages/student/StudentProfilePage.tsx
src/pages/user/LoginPage.tsx
src/store/LectureSlice.tsx

- feat: alert 추가 및 수정 폼 뒤로가기 추가, 디자인 수정
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: alert 추가 및 수정 폼 뒤로가기 추가, 디자인 수정

---

src/components/quiz/QuizBlock.tsx
src/components/quiz/StatisticsChart.tsx

- 퀴즈 통계 화면 하얗게 변하는 오류 수정
- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 순위 통계 로컬스토리지에 저장하도록 변경

---

src/components/student/ProfileLectureHistory.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 학생 강의 히스토리 연동

---

package-lock.json
src/App.tsx
src/api/lecture/lectureAPI.ts
src/api/user/userAPI.ts
src/components/student/CareerRecommendation.tsx
src/components/student/MyLecturePreference.tsx
src/components/teacher/teacherMyLecture/TeacherMyLectureListButton.tsx
src/interface/profile/StudentProfileInterface.tsx
src/pages/teacher/TeacherProfilePage.tsx
src/store/LectureSlice.tsx
src/store/userInfo/StudentProfileSlice.tsx

- feat: 강의 레포트 기능 구현 중
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 강의 레포트 기능 구현 중

---

src/pages/classroom copy/WebrtcStudent.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 학생 퀴즈 rtc 연동

---

src/components/quiz/QuizBlock.tsx
src/components/quiz/RankingList.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

퀴즈 순위 변경되는 애니메이션 에러 해결

---

src/components/quiz/RankingList.tsx
src/pages/classroom copy/WebrtcStudent.tsx
src/pages/classroom copy/WebrtcTeacher.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

선생님 퀴즈 실시간으로 학생들에게 emit, 퀴즈모달 띄워지게 하는 기능 구현

---

src/pages/classroom/WebrtcStudent.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix: 학생측 퀴즈 안띄워지는 오류 수정

---

src/components/quiz/QuizBlock.tsx
src/components/quiz/RankingList.tsx
src/pages/classroom/WebrtcStudent.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

퀴즈 에러 수정, 디자인 개선

---

src/components/teacher/quiz/CreateQuiz.tsx
src/components/teacher/quiz/FetchQuiz.tsx
src/components/teacher/quiz/PatchQuiz.tsx
src/pages/classroom/WebrtcStudent.tsx

- feat: 퀴즈 조회, 생성, 수정 폼에서 각각 목록 페이지로 가는 버튼 생성
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

feat: 퀴즈 조회, 생성, 수정 폼에서 각각 목록 페이지로 가는 버튼 생성

---

src/components/lecture/SignUp.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix: 커리큘럼 생성 시 카테고리 숫자로 들어가는 오류 수정

---

src/components/student/ProfileLectureHistory.tsx

- 
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<hr>

fix;: 강의 히스토리 안나오는 오류 수정
